src/Styles/StyledButtons.js, src/Styles/StyledDashboardForms.js, src/components/AnswerFormView.jsx, src/components/DashboardForms.jsx
Front: añadí estilos a los componentes DashboarForm y AnswerForm.
=> Front-add-styles-to-DashboardForm-julian

src/Styles/StyledButtons.js, src/Styles/StyledDashboardForms.js, src/components/AnswerFormView.jsx, src/components/DashboardForms.jsx
Front: añadiendo más estilos a componente DashboardForm
=> Front-add-more-styles-to-DashboarForm-julian

src/Styles/StyledAnswersView.js, src/components/AnswerFormView.jsx, src/components/DashboardForms.jsx
Front: añadiendo más estilos y solucionando bug en delete forms
=> Front-add-styles-component-julian

src/Styles/StyledAnswersView.js, src/Styles/StyledButtons.js, src/Styles/StyledDashboardForms.js, src/components/DashboardCreateForm.jsx
Front: bug del delete de formulario resuelto y se añade estilos a componente DashboardCreateForm
=> Front-and-add-styles-createForm-julian

src/components/DashboardCreateForm.jsx
Front: refactorización de estilo al componente DashboardCreateForm
=> Front-refactor-style-to-DashboarCreateForm-julian

src/Redux/Actions/index.js, src/components/AnswerFormView.jsx, src/components/DashboardForms.jsx, src/utils/constant.js
Front: refactorización de componente AnswersFormView agregando action setFormStatus part1
=> Front-refactor-AnswerForm-action-setFormStatus-jul

src/components/EditableRows.jsx, src/components/PetsInDashboard.jsx, src/components/ReadOnlyRows.jsx
cambios front selectores para edicion de mascotas
=> cambios front selectores para edicion de mascotas

src/Redux/Actions/index.js, src/components/DashboardForms.jsx, src/components/FormAdoption.jsx, src/components/FormTransit.jsx
Front: bugs en componente DashboardForm resuelto
=> Front-bugs-resolved-of-components-julian

src/components/PetsInDashboard.jsx
added async await to handleEdit to update pet info
=> added async await to handleEdit

src/Styles/StyledButtons.js, src/components/AnswerFormView.jsx, src/components/DashboardForms.jsx
Front: se resuelve bug de componente dashboardForm
=> front-bugs-resolved-component-Dashboard-U.U

src/components/PetsInDashboard.jsx, src/utils/constant.js
cambio a funcion asincrona de handleDelete
=> cambio a funcion asincrona de handleDelete

src/Styles/StyledDashboardForms.js, src/components/DashboardForms.jsx, src/utils/constant.js
Front: se resuelve totalmente bugs, delays y toda clase de cosa relacionada con el DashboardForm U.U
=> Front-profin-dejé-DashboardForm-descente-U.U-juli

src/Styles/StyledSimilarPets.js, src/components/SimilarPets.jsx
Más recomendaciones del refugio
=> ...UPDATE Más recomendaciones del refugio

src/components/AnswerFormView.jsx, src/components/Filters.jsx
=> Front-test-final-part1-julian

src/Redux/Reducer/index.js, src/components/Filters.jsx
Front: refcatorizando ruta de filter para que solo muestre en adopción y colocando filtro por géneros
=> Front-refactor-filters-julian

src/Styles/StyledDivFlexrow.js, src/components/DashboardCreateForm.jsx
Front: añadiendo algunos estilos a el componente DashboarCreateForm
=> Front-add-some-styles-to-DashboarCreateForm-julian

src/components/EditableRowsFollowUp.jsx, src/components/FollowUp.jsx, src/components/ReadOnlyRowsFollowUp.jsx
refactor a front followUp pets
=> refactor a front followUp pets

src/DashboardRoutesAdmin.js, src/Styles/StyledDashboardPetAdmin.js, src/components/AnswerFormView.jsx, src/components/DashboardPetAdmin.jsx
Front: se crea el componente DashboardPetAdmin, solo la parte visual, no está funcional.
=> Front-component-DashboarPetAdmin-only-visual-juli

src/Styles/StyledAnswersView.js, src/Styles/StyledDashboardPetAdmin.js, src/components/DashboardAdmin.jsx, src/components/DashboardPetAdmin.jsx, src/utils/constant.js
Front: acomodando algunos detalles
=> Front-refactor-visual-of-my-components-julian

src/Styles/StyledPetsInDashboard.js, src/components/EditableRowsFollowUp.jsx, src/components/FollowUp.jsx
=> refactor followUp dates

src/DashboardRoutes.js, src/Styles/StyledFollowUpTransit.js, src/components/Dashboard.jsx, src/components/FollowUpTransit.jsx, src/utils/constant.js
creacion de componente y ruta FollowUpTransit
=> creacion de componente FollowUpTransit

src/Redux/Reducer/index.js, src/components/DashboardPetAdmin.jsx
Front: acciones de filtros para DashboradPetAdmin completado part 4. falta ordenamiento y editar.
=> Front-DashbPetAdminf-part4--filters-finished-juli

src/Styles/StyledFollowUpTransit.js, src/components/EditableRowsTransit.jsx, src/components/FollowUpTransit.jsx, src/components/ReadOnlyRowsTransit.jsx
Renderizado de datos para hogares tránsito
=> Renderizado de datos para hogares tránsito

src/components/AnswerFormView.jsx
Front: número uno removido exitosamente.
=> Front-number-one-successfully-removed-julian

src/Redux/Reducer/index.js
Front-error en el redux resuuelto
=> Front-solved-error-redux-julian

src/Styles/StyledDashboardPetAdmin.js, src/components/DashboardPetAdmin.jsx, src/components/DashboardPetEditAdmin.js, src/utils/constant.js
Front: parte 7 del DashboardPetAdmin
=> Front-part7-DashboardPetAdmin-julian

src/Styles/StyledFollowUpTransit.js, src/components/EditableRowsTransit.jsx, src/components/FollowUpTransit.jsx
Avances a componente FollowUpTransits, ya aparecen opciones desplegables. Y se van desapareciendo despues de haber sido seleccionadas.
=> avances a componente FollowUpTransits

src/components/EditableRows.jsx, src/components/FollowUpTransit.jsx, src/components/PetsInDashboard.jsx, src/components/ReadOnlyRows.jsx
correcion de bug al hacer filter en petsInDashboard
=> correcion de bug al hacer filter

src/components/EditableRowsTransit.jsx
se agrega funcionalidad deletePetFromList
=> se agrega funcionalidad deletePetFromList

src/Styles/StyledAdminLogin.js, src/components/LoginAdmin.jsx
Front: estilo de login de admin refactorizado
=> Front-solved-login-style-julian

src/Styles/StyledAnswersView.js, src/Styles/StyledDashboardForms.js, src/components/DashboardCreateForm.jsx, src/components/DashboardForms.jsx
Front: refactor de estilos de componentes de formularios
=> Front-refactor-forms-components-julian

src/Styles/StyledPetsInDashboard.js
Fron: refactor a botón de modal en pets
=> Front-refactor-style-to-modal-pets-julian

src/components/ReadOnlyRowsTransit.jsx
=> refactor readOnlyRows

src/components/FollowUpTransit.jsx
solucion de bugs followUpTransit
=> solucion de bugs followUpTransit

src/components/EditableRowsTransit.jsx
renderizado de  nombres de mascotas followUpTransit
=> renderizado de  nombres de mascotas followUpTransit

src/Styles/StyledCreatePets.js, src/components/CreatePets.jsx, src/utils/constant.js
Front: refactor componente createPet
=> Front-refactor-createPet-julian

src/components/DashboardPetAdmin.jsx
Fron: bug en componente DashboardPetAdmin resuelto
=> Front-resolve-bug-in-DashboardPetAdmin

src/Styles/StyledFollowUpTransit.js, src/Styles/StyledPetsInDashboard.js, src/components/EditableRowsTransit.jsx, src/components/FollowUpTransit.jsx, src/components/ReadOnlyRowsTransit.jsx
=> estilos a FollowUpTransits

src/components/DashboardPetAdmin.jsx
front: refactor de DashboardPetAdmin
=> front-refactor-Dashboard

src/Styles/StyledPetsInDashboard.js, src/components/EditableRows.jsx, src/components/ReadOnlyRows.jsx
=> estilos para PetsInDashboard

src/Styles/StyledCreatePets.js, src/Styles/StyledPetsInDashboard.js
=> front-styles

src/components/EditableRowsFollowUp.jsx, src/components/FollowUp.jsx, src/components/ReadOnlyRowsFollowUp.jsx
=> mas estilos Front

src/Redux/Actions/index.js
FRONT se agrega alerta al despachar action MH
=> FRONT se agrega alerta al despachar action MH

src/components/DashboardCreateForm.jsx, src/components/DashboardForms.jsx
Front: refactor a algunas cosas en componentes DashboardForm y createForm
=> Front-refactor-styles-to components

src/Styles/StyledPetsInDashboard.js, src/components/PetsInDashboard.jsx
=> front-resolved-button-petInDashboard-julian

src/components/CreatePets.jsx, src/utils/constant.js
=> front-refactor-style

src/components/AnswerFormView.jsx
=> front-julian

src/Styles/StyledButtons.js
=> Front-ff-julian

src/Styles/StyledFollowUpTransit.js, src/Styles/StyledPetsInDashboard.js, src/components/DashboardIcos.jsx, src/components/EditableRows.jsx, src/components/PetsInDashboard.jsx, src/components/ReadOnlyRows.jsx
=> cambios a estilos

src/Styles/StyledPetsInDashboard.js, src/components/EditableRows.jsx, src/components/FollowUp.jsx, src/components/ReadOnlyRows.jsx
=> cambios front estilos

src/components/PetsInDashboard.jsx
cambio estilo boton petsInDashboard
=> cambio estilo boton petsInDashboard
